version: '2'
networks:
  wktech-network:
    external: true
services:
  wktech_app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: wktech
    container_name: wktech-web
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - wktech-network
  wktech_nginx:
    image: nginx:1.17-alpine
    container_name: wktech-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - wktech-network
  wktech_db:
    image: mysql/mysql-server:8.0.23
    container_name: wktech-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - wktech-network
    ports:
      - 3306:3306